### ISSUE TITLE
Import errors with ollama-0.4.0

### ISSUE THREAD

**Issue by walcode** [ggozad/oterm#139]
Hi thank you for all your work on the great project.

New install using pip in a venv installs ollama-0.4.0 by default which gives the below errors.  Downgrading to ollama-0.3.3 resolves the problem.

Traceback (most recent call last):
  File "/home/user/oterm_venv/bin/oterm", line 5, in <module>
    from oterm.cli.oterm import cli
  File "/home/user/oterm_venv/lib/python3.11/site-packages/oterm/cli/oterm.py", line 7, in <module>
    from oterm.app.oterm import app
  File "/home/user/oterm_venv/lib/python3.11/site-packages/oterm/app/oterm.py", line 10, in <module>
    from oterm.app.chat_edit import ChatEdit
  File "/home/user/oterm_venv/lib/python3.11/site-packages/oterm/app/chat_edit.py", line 17, in <module>
    from oterm.ollamaclient import OllamaLLM, parse_ollama_parameters
  File "/home/user/oterm_venv/lib/python3.11/site-packages/oterm/ollamaclient.py", line 16, in <module>
    from oterm.tools import ToolDefinition
  File "/home/user/oterm_venv/lib/python3.11/site-packages/oterm/tools/__init__.py", line 3, in <module>
    from ollama._types import (
ImportError: cannot import name 'Parameters' from 'ollama._types' (/home/user/oterm_venv/lib/python3.11/site-packages/ollama/_types.py)

**Comment by ggozad** [comment]
Hey @walcode 
Thanks for the heads up, seems like ollama-python changed the definition of tool-related classes. 
I will adapt and release asap.
In the meantime, downgrading to 0.3.3 is indeed the workaround.

**Comment by ggozad** [comment]
I released for the meantime 0.6.9 pinning ollama to <0.4 as there are a number of breaking changes.
Will keep this open till I release an update for 0.4.
