### ISSUE TITLE
oterm not running: FileNotFoundError (config.json)

### ISSUE THREAD

**Issue by cccrc** [ggozad/oterm#47]
Hi,

I installed via 'pip install oterm'  on both Ubuntu and Debian in WSL on command 'oterm' I get:

(env) xyz@abc:~$ oterm
Traceback (most recent call last):
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/config.py", line 79, in __init__
    with open(self._path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/xyz/.local/share/oterm/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyz/env/bin/oterm", line 5, in <module>
    from oterm.cli.oterm import cli
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/cli/oterm.py", line 6, in <module>
    from oterm.app.oterm import app
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/app/oterm.py", line 6, in <module>
    from oterm.app.model_selection import ModelSelection
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/app/model_selection.py", line 13, in <module>
    from oterm.ollama import OllamaAPI
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/ollama.py", line 6, in <module>
    from oterm.config import envConfig
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/config.py", line 99, in <module>
    appConfig = AppConfig()
                ^^^^^^^^^^^
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/config.py", line 83, in __init__
    self.save()
  File "/home/xyz/env/lib/python3.11/site-packages/oterm/config.py", line 93, in save
    with open(self._path, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/xyz/.local/share/oterm/config.json'

**Comment by ggozad** [comment]
Sorry about that, will fix and release.

**Comment by cccrc** [comment]
Thanks man, great work!
