### ISSUE TITLE
Module 'httpcore' has no attribute 'Request'

### ISSUE THREAD

**Issue by icarosadero** [ggozad/oterm#62]
I installed oterm via pip and got this error.

```
Traceback (most recent call last):
  File "/usr/local/bin/oterm", line 5, in <module>
    from oterm.cli.oterm import cli
  File "/usr/local/lib/python3.10/dist-packages/oterm/cli/oterm.py", line 6, in <module>
    from oterm.app.oterm import app
  File "/usr/local/lib/python3.10/dist-packages/oterm/app/oterm.py", line 7, in <module>
    from oterm.app.chat_edit import ChatEdit
  File "/usr/local/lib/python3.10/dist-packages/oterm/app/chat_edit.py", line 14, in <module>
    from oterm.ollama import OllamaAPI
  File "/usr/local/lib/python3.10/dist-packages/oterm/ollama.py", line 4, in <module>
    import httpx
  File "/usr/local/lib/python3.10/dist-packages/httpx/__init__.py", line 48, in <module>
    from ._main import main
  File "/usr/local/lib/python3.10/dist-packages/httpx/_main.py", line 111, in <module>
    def format_request_headers(request: httpcore.Request, http2: bool = False) -> str:
AttributeError: module 'httpcore' has no attribute 'Request'

```

**Comment by icarosadero** [comment]
After investigating the issue, it was discovered that the problem was caused by conflicting version requirements of httpx between two dependent packages: mugmoment required httpx<0.18.0, while oterm required httpx>=0.25.0.

To resolve the conflict, I downgraded httpx to version 0.25.1, which satisfied the version requirement of both packages. I ran the following command to downgrade httpx:

```
pip install "httpx<0.26.0"
```

After downgrading httpx, I was able to run oterm successfully.

**Comment by ggozad** [comment]
Hey there,
know you solved your problem, just some advice for the future :)
You are going to have a bad time if you install with `pip` globally. It's never a good idea to have anything really other than pip and pipx installed globally.
Use a virtual environment instead or `pipx`!
